package main.java.problem_2;

public class problem_2 {
    /*
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
     */

    public static long ans() {
        return internal(4000000);
    }

    public static int internal(int x) {
        int x0 = 1;
        int x1 = 2;
        int temp;
        int counter = 0;
        while (true) {
            if (x1 % 2 == 0) {
                counter += x1;
            }
            temp = x1;
            x1 += x0;
            x0 = temp;
            if (x1 > x) {
                break;
            }
        }
        return counter;
    }
}
